baseURL = ""
languageCode = "en-us"
title = "AWS Lambda - Serverless"
theme = "ananke"

[params.lambdaComments]
endpoint = "https://2u3oylcl7c.execute-api.eu-west-3.amazonaws.com/default/student50-comments-post"
